"use strict";
/*Conditional Tests: Write a series of conditional tests. Print a statement describing each test and
your prediction for the results of each test.*/
let car = "Toyota";
console.log("Is car == 'Toyota'? I predict True.");
console.log(car == "Toyota");
let mobile = "iphone";
console.log("Is mobile == 'Iphone'? I predict False.");
console.log(mobile == "Iphone");
let birthdayNumber = 4;
console.log("Is Birthday Number == 4? I predict True.");
console.log(birthdayNumber == 4);
let city = "Tokyo";
console.log("Is city == 'TOKYO'? I predict False.");
console.log(city == "TOKYO");
let minNumber = 3;
console.log("Is Min Number greater than 2? I predict True.");
console.log(minNumber > 2);
let quantity = 3;
console.log("Is quantity greater than 4? I predict False.");
console.log(quantity > 4);
let sum = 8 + 3;
console.log("Is the sum 11'? I predict True.");
console.log(sum == 11);
let country = "turkey";
console.log("Is country in uppercase equals TURKEY? I predict True.");
console.log(country.toUpperCase() == "TURKEY");
let age = 19;
console.log("Is less than or equal to 18? I predict False.");
console.log(age <= 18);
let color = "red";
console.log("Is color white? I predict False.");
console.log(color == "white");
